name: Java CI

on:
  push:
    branches:
      - 'Pongkrit'  # Correct indentation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1  # Change to 1 since env.PR_FETCH_DEPTH might not be defined

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Verify Directory Structure
        run: ls -R

      - name: Compile Java
        run: |
          PROJECT_DIR="HolidayTravelVehicles"
          if [ -d "$PROJECT_DIR" ]; then
            echo "Directory $PROJECT_DIR found."
            cd $PROJECT_DIR
            javac -d . *.java
          else
            echo "Error: Directory $PROJECT_DIR not found!"
            exit 1
          fi
